# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: 'containers'
  cookie_secret: 'e7247dae-a252-4393-afa3-2219c1c02efd'
  session_expiry: 86400

  cc_api_uri: 'http://api.vcap.me'
  external_ip: 54.175.17.34
  external_host: ec2-54-175-17-34.compute-1.amazonaws.com

  ssl_enabled: false
  skip_ssl_validation: true

  host_directory: '/var/vcap/store/cf-containers-broker/'
  max_containers: 0
  allocate_docker_host_ports: false
  container_env_var_dir: '/var/vcap/store/cf-containers-broker/envdir'

  services:
    - id: '23eefc93-6814-4db8-bbf0-eaa6c3c5fecc'
      name: 'easytravel-mongodb'
      description: 'MongoDB service for Dynatrace easyTravel'
      bindable: true
      tags:
        - 'mongodb'
        - 'easyTravel'
      metadata:
        displayName: 'A pre-populated MongoDB service for Dynatrace easyTravel'
        longDescription: 'A pre-populated MongoDB service for the Dynatrace easyTravel demo application'
        providerDisplayName: 'Dynatrace LLC'
        documentationUrl: 'https://github.com/dynatrace/Dynatrace-easyTravel-Docker'
        supportUrl: 'https://github.com/dynatrace/Dynatrace-easyTravel-Docker/issues'
      dashboard_client:
        id: 'p-postgresql93-client'
        secret: 'p-postgresql93-secret'
        redirect_uri: 'http://127.0.0.1:3000/manage/auth/cloudfoundry/callback'
      plans:
        - id: '6d8024b1-7deb-4dc7-a72a-33ec3f7a1bfc'
          name: 'free'
          container:
            backend: 'docker'
            image: 'dynatrace/easytravel-mongodb'
          credentials:
            username:
              key: 'MONGODB_USERNAME'
              value: 'labuser'
            password:
              key: 'MONGODB_PASSWORD'
              value: 'labpass'
            dbname:
              key: 'MONGODB_DBNAME'
              value: 'easyTravel-Business'
            uri:
              prefix: 'mongodb'
              port: '27017/tcp'
          description: 'Free Trial'
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: 'MONTHLY'

assets:
  auth_password: 'secret'
  <<: *defaults

development:
  auth_password: 'secret'
  <<: *defaults

test:
  auth_password: 'secret'
  <<: *defaults
