# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: 'containers'
  cookie_secret: 'e7247dae-a252-4393-afa3-2219c1c02efd'
  session_expiry: 86400

  cc_api_uri: 'http://api.vcap.me'
  external_ip: 127.0.0.1
  external_host: 'containers.vcap.me'

  ssl_enabled: false
  skip_ssl_validation: true

  host_directory: '/var/vcap/store/cf-containers-broker/'
  max_containers: 0
  allocate_docker_host_ports: false
  container_env_var_dir: '/var/vcap/store/cf-containers-broker/envdir'

  services:
    - id: '23eefc93-6814-4db8-bbf0-eaa6c3c5fecc'
      name: 'mongodb-easytravel'
      description: 'MongoDB 2.6 service for Dynatrace easyTravel'
      bindable: true
      tags:
        - 'mongodb'
        - 'easyTravel'
      metadata:
        displayName: 'MongoDB 2.6 for Dynatrace easyTravel'
        longDescription: 'A MongoDB 2.6 service for the Dynatrace easyTravel demo application'
        providerDisplayName: 'Pivotal Software'
        documentationUrl: 'https://github.com/dynatrace-innovationlab/easyTravel-Cloud-Foundry'
        supportUrl: 'https://github.com/dynatrace-innovationlab/easyTravel-Cloud-Foundry/issues'
      dashboard_client:
        id: 'p-mongodb26-client'
        secret: 'p-mongodb26-secret'
        redirect_uri: 'http://cf-containers-broker.run.pivotal.io/manage/auth/cloudfoundry/callback'
      plans:
        - id: '6d8024b1-7deb-4dc7-a72a-33ec3f7a1bfc'
          name: 'free'
          container:
            backend: 'docker'
            image: 'frodenas/mongodb'
            tag: '2.6'
            command: '--smallfiles --httpinterface'
            persistent_volumes:
              - '/easyTravel-data'
          credentials:
            username:
              key: 'MONGODB_USERNAME'
              value: 'labuser'
            password:
              key: 'MONGODB_PASSWORD'
              value: 'labpass'
            dbname:
              key: 'MONGODB_DBNAME'
              value: 'easyTravel-Business'
            uri:
              prefix: 'mongodb'
              port: '27017/tcp'
          description: 'Free Trial'
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: 'MONTHLY'
            bullets:
              - 'MongoDB 2.6 for Dynatrace easyTravel running inside a Docker container'

assets:
  auth_password: 'secret'
  <<: *defaults

development:
  auth_password: 'secret'
  <<: *defaults

test:
  auth_password: 'secret'
  <<: *defaults
